# Matugen generated colors for Kitty
# Basic colors
foreground            #e1e2e8
background            #111418
selection_foreground  #00325a
selection_background  #a1c9fd

# Cursor
cursor                #a1c9fd
cursor_text_color     #00325a

# URL underline color when hovering
url_color             #d7bde4

# 16 ANSI colors
# Black
color0  #1d2024
color8  #32353a

# Red
color1  #ffb4ab
color9  #ffb4ab

# Green
color2  #d7bde4
color10 #533f5f

# Yellow
color3  #bbc7db
color11 #d7e3f8

# Blue
color4  #a1c9fd
color12 #1b4975

# Magenta
color5  #d7bde4
color13 #f3daff

# Cyan
color6  #3c4858
color14 #d7e3f8

# White
color7  #e1e2e8
color15 #e1e2e8
