# ========================================
# SYSTEM FIXES
# ========================================
# windowrule = nofocus on, match:class ^$, match:title ^$, xwayland:1, floating:1, fullscreen:0, pinned:0

# ========================================
# ZEN BROWSER
# ========================================
windowrule = workspace 2, match:class ^(zen)$
windowrule = maximize on, match:class ^(zen)$

# ========================================
# POSTMAN
# ========================================
windowrule = workspace 3, match:class ^(Postman)$

# ========================================
# FILE MANAGER
# ========================================
windowrule = float on, match:class ^(thunar)$
windowrule = size 900 600, match:class ^(thunar)$
windowrule = center on, match:class ^(thunar)$

# ========================================
# FLOATING SYSTEM DIALOGS
# ========================================
windowrule = float on, match:title ^(Open File)$
windowrule = float on, match:title ^(Save File)$
windowrule = float on, match:title ^(File Upload)$
windowrule = center on, match:title ^(Open File)$
windowrule = center on, match:title ^(Save File)$
windowrule = center on, match:title ^(File Upload)$

# ========================================
# PICTURE IN PICTURE
# ========================================
windowrule = float on, match:title ^(Picture-in-Picture)$
windowrule = pin on, match:title ^(Picture-in-Picture)$
windowrule = size 480 270, match:title ^(Picture-in-Picture)$
windowrule = move 1430 780, match:title ^(Picture-in-Picture)$
