# ========================================
# AUTOSTART APPLICATIONS
# Applications launched at Hyprland startup
# ========================================

exec-once = waybar
exec-once = hyprpolkitagent
exec-once = swww-daemon
# exec-once = ~/.config/hypr/scripts/wallpaper.sh $wallpaperDir/Black/lofi.gif
# exec-once = swww img exec-once = udiskie --appindicator -t
exec-once = bash -c 'sleep 1 && LAST=$(cat ~/.cache/current-wallpaper 2>/dev/null || echo "$HOME/Pictures/Wallpapers/Black/lofi.gif") && ~/.config/hypr/scripts/wallpaper.sh "$LAST"'
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
