general {
    gaps_in = 4
    gaps_out = 8
    border_size = 0
    col.active_border = rgba(9acbfaee)
    col.inactive_border = rgba(00000000)
}

decoration {
    rounding = 12
    
    blur {
        enabled = true
        size = 6
        passes = 3
        new_optimizations = true
        xray = false
        ignore_opacity = false
    }
    
    shadow {
        enabled = true
        range = 20
        render_power = 3
        color = rgba(00000066)
    }
}
